language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install: 
  - npm install -g hexo
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - npm install -g mocha
  - git clone --branch master https://github.com/jackey8616/jackey8616.github.io.git public

script: 
  - hexo cl
  - hexo g

after_script: 
  - cd ./public 
  - git init 
  - git config user.name "clo5de"
  - git config user.email "jackey8616@gmail.com"
  - git add . 
  - git commit -m "update by Travis-CI" 
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches: 
  only: 
    - blog

env: 
  global: 
    - GH_REF: github.com/jackey8616/jackey8616.github.io.git

